services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  init-db:
    build:
      context: ./init-db
    depends_on:
      - mysql
  
  frontend:
    build:
      context: ./frontend/tfg-frontend
    ports:
      - "5173:5173" 
      - "8080:8080"
    # volumes:
      # - frontend-development:/app
  
  backend:
    build:
      context: ./backend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    volumes:
      - backend-files:/app/files
      - ml-module-files:/app/ml_module

  ml_module:
    build:
      context: ./ML_module
    depends_on:
      - backend
    volumes:
      - backend-files:/app/files
      - ml-module-files:/app/ml_module
volumes:
  backend-files:
  ml-module-files:
  # frontend-development: