FROM node:latest

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# for testing with no working register
ENV NODE_ENV "development"

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

# Expose the port
EXPOSE 8080

# Run Express server
CMD ["node", "server.js"]