FROM python:3-alpine

# Instalar las dependencias necesarias
RUN apk add --no-cache mariadb-connector-c-dev
RUN pip install mysql-connector-python

WORKDIR /app

COPY init-db.py .

CMD ["python", "init-db.py"]
