version: "3.4"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  init-db:
    build:
      context: ./init-db
    depends_on:
      - mysql
