version: "3.4"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./db-volume:/var/lib/mysql
  
  front:
    image: node
