FROM python:3

WORKDIR /app

COPY requirements.txt .
COPY tfg_backend.py .

RUN apt-get update && apt-get install libgl1 -y
RUN pip install -r "requirements.txt"

EXPOSE 8081
CMD ["python", "tfg_backend.py"]